# Per-product marketing descriptions, keyed by exact product name.
# Used by seed.py (so re-seeding keeps them) and shown on the product detail page.

DESCRIPTIONS = {
    # ---------------- Fruits ----------------
    "Apple (सेब)": "Crisp, juicy apples with the perfect balance of sweet and tart. Great for everyday snacking, fruit salads, and lunchboxes.",
    "Banana (केला)": "Naturally sweet, energy-rich bananas ripened to perfection. Perfect for breakfast, smoothies, shakes, and quick snacking.",
    "Black Grapes (अंगूर - काले)": "Plump, deep-purple grapes bursting with sweet juice. Perfect for snacking, fruit bowls, and fresh juices.",
    "Chikoo / Sapota (चीकू)": "Soft, grainy-sweet chikoo with a rich malty flavour. Perfect for eating fresh, milkshakes, and desserts.",
    "Coconut / Nariyal (नारियल)": "Farm-fresh mature coconut with thick, flavourful flesh. Perfect for chutneys, curries, and festive cooking.",
    "Green Grapes (अंगूर - हरे)": "Crisp, seedless green grapes with a refreshing sweet-tart taste. Perfect for snacking, salads, and juicing.",
    "Guava (अमरूद)": "Fragrant, crunchy guavas packed with vitamin C. Perfect for eating fresh with a pinch of masala, or for juices.",
    "Indian Gooseberry / Amla (आंवला)": "Tangy, vitamin-rich amla straight from the farm. Perfect for pickles, murabba, juices, and immunity-boosting home remedies.",
    "Indian Jujube / Ber (बेर)": "Crunchy, sweet-tart ber with a refreshing bite. Perfect for snacking and traditional winter treats.",
    "Jamun (जामुन)": "Juicy, deep-purple jamun with a sweet-astringent taste. Perfect for snacking and seasonal summer refreshment.",
    "Lemon / Nimbu (नीम्बू)": "Juicy, aromatic lemons full of tang. Perfect for nimbu paani, dals, marinades, and everyday cooking.",
    "Lychee (लीची)": "Fragrant, juicy lychees with translucent sweet flesh. Perfect for eating fresh, desserts, and summer coolers.",
    "Mango (आम)": "Sweet, aromatic mangoes — the king of fruits at peak ripeness. Perfect for eating fresh, shakes, and aamras.",
    "Muskmelon / Kharbooja (खरबूजा)": "Fragrant, honey-sweet muskmelon with juicy orange flesh. Perfect for summer snacking, smoothies, and fruit bowls.",
    "Orange / Santra (संतरा)": "Juicy, tangy-sweet oranges loaded with vitamin C. Perfect for fresh juice, snacking, and fruit salads.",
    "Papaya (पपीता)": "Ripe, buttery-sweet papaya rich in fibre and enzymes. Perfect for breakfast bowls, smoothies, and healthy snacking.",
    "Pear / Nashpati (नाशपाती)": "Crisp, mildly sweet pears with a refreshing juicy bite. Perfect for snacking, salads, and lunchboxes.",
    "Pineapple / Ananas (अनानास)": "Tangy-sweet, aromatic pineapple with golden juicy flesh. Perfect for fresh slices, juices, and fruit chaat.",
    "Pomegranate / Anaar (अनार)": "Ruby-red pomegranate arils bursting with sweet-tart juice. Perfect for snacking, salads, raita, and juices.",
    "Raw Mango / Kacche Aam (कच्चे आम)": "Firm, tangy raw mangoes with a sharp sour bite. Perfect for aam panna, pickles, and chutneys.",
    "Safeda Mango (आम सफेदा)": "Smooth, fibreless safeda mangoes with rich sweetness. Perfect for eating fresh, shakes, and aamras.",
    "Shimla Apple (सेब - शिमला)": "Crunchy, deep-red Shimla apples with a sweet-tart crunch. Perfect for snacking, salads, and lunchboxes.",
    "Sugarcane / Ganna (गन्ना)": "Fresh, juicy sugarcane full of natural sweetness. Perfect for fresh ganna juice and traditional refreshment.",
    "Sweet Lime / Mosambi (मौसम्बी)": "Juicy, mildly sweet mosambi packed with vitamin C. Perfect for fresh juice and a light, refreshing drink.",
    "Tender Coconut (नारियल वाला पानी)": "Fresh tender coconut with sweet, hydrating water and soft malai. Perfect for a naturally refreshing, healthy drink.",
    "Watermelon (तरबूज)": "Crisp, deep-red watermelon with sweet, hydrating juice. Perfect for summer snacking, juices, and fruit bowls.",

    # ---------------- Vegetables ----------------
    "Ash Gourd / White Pumpkin (सफेद पेठा)": "Fresh ash gourd with mild flavour and tender flesh. Perfect for petha, kootu, sambar, and cooling summer dishes.",
    "Beetroot / Chukandar (चुकंदर)": "Earthy, deep-red beetroots packed with nutrients. Perfect for salads, juices, sabzi, and healthy raita.",
    "Bhangar Brinjal (भांगर बैंगन)": "Glossy long brinjals with tender flesh and few seeds. Perfect for bharta, curries, and stir-fries.",
    "Bitter Gourd / Karela (करेला)": "Fresh, firm karela with the classic sharp taste. Perfect for stuffed sabzi, fries, and healthy everyday cooking.",
    "Bottle Gourd / Lauki (लौकी)": "Tender, light-green lauki with soft flesh. Perfect for sabzi, kofta, dal, and comforting home meals.",
    "Brinjal / Baingan (बैंगन)": "Glossy, firm brinjals with rich flavour. Perfect for bharta, bharwan baingan, and everyday curries.",
    "Broad Beans / Sem ki Phali": "Tender, flat sem pods with a mild nutty taste. Perfect for stir-fries and hearty winter sabzis.",
    "Broad Beans Pods (बाकला की फली)": "Fresh broad bean pods with plump, buttery beans. Perfect for sabzi, stir-fries, and traditional recipes.",
    "Cabbage / Patta Gobi (पत्ता गोभी)": "Crisp, tightly-packed cabbage with a fresh crunch. Perfect for sabzi, salads, stir-fries, and rolls.",
    "Cauliflower (फूलगोभी)": "Fresh, snow-white cauliflower with firm florets. Perfect for aloo gobi, parathas, pakoras, and stir-fries.",
    "Chipsona Potato (चिपसोना आलू)": "Starchy chipsona potatoes ideal for crisp results. Perfect for fries, chips, and crunchy snacks.",
    "Cluster Beans / Guar Pods (ग्वार की फली)": "Tender guar pods with a mild, earthy taste. Perfect for dry sabzi and traditional home-style cooking.",
    "Colocasia / Taro Root / Arbi (अरबी)": "Firm arbi roots with a soft, creamy texture when cooked. Perfect for fry, masala sabzi, and snacks.",
    "Cowpea Beans / Yardlong Beans (लोबिया की फली)": "Crisp, long cowpea beans with a fresh snap. Perfect for stir-fries and everyday sabzi.",
    "Deshi Garlic (देसी लहसुन)": "Pungent, aromatic desi garlic with small, flavour-packed cloves. Perfect for tadka, chutneys, and everyday cooking.",
    "Deshi Pointed Gourd / Deshi Parwal (देसी परवल)": "Tender desi parwal with a mild, pleasant taste. Perfect for bhujia, dorma, and light curries.",
    "Deshi Tomato (टमाटर)": "Tangy, juicy desi tomatoes with rich flavour. Perfect for gravies, chutneys, salads, and everyday cooking.",
    "Drumstick / Sahjan (सहजन)": "Fresh, tender drumsticks full of flavour and nutrients. Perfect for sambar, dal, and South Indian curries.",
    "Elephant Foot Yam / Jimikand (जिमीकंद)": "Firm jimikand with a hearty texture. Perfect for fry, masala sabzi, and traditional festive dishes.",
    "English Cucumber / Kheera (खीरा)": "Cool, crisp cucumber with refreshing juicy flesh. Perfect for salads, raita, and healthy summer snacking.",
    "French Beans (फ्रेंच बींस)": "Crunchy, tender french beans with a fresh snap. Perfect for stir-fries, poriyal, and mixed veg.",
    "Fresh Turmeric / Haldi (ताज़ी हल्दी)": "Aromatic fresh turmeric roots with vibrant colour. Perfect for pickles, chutneys, and immunity drinks.",
    "Garlic / Mota Lehsun (मोटा लहसुन)": "Bold, aromatic garlic with large, easy-to-peel cloves. Perfect for tadka, gravies, and everyday cooking.",
    "Ginger / Adrak (अदरक)": "Fresh, pungent ginger with a warm, zesty kick. Perfect for chai, curries, and home remedies.",
    "Green Capsicum / Shimla Mirch (शिमला मिर्च)": "Crunchy green capsicum with a mild, fresh flavour. Perfect for stir-fries, curries, and pizza toppings.",
    "Green Chilli / Hari Mirch (हरी मिर्च)": "Fresh, fiery green chillies with a sharp kick. Perfect for tadka, chutneys, and adding heat to any dish.",
    "Hill Potato / Pahadi Aloo (पहाड़ी आलू)": "Wholesome hill potatoes with a rich, earthy taste. Perfect for curries, parathas, and everyday cooking.",
    "Hybrid Cucumber (हाइब्रिड खीरा)": "Crisp hybrid cucumbers with tender skin and juicy flesh. Perfect for salads, raita, and refreshing snacks.",
    "Hybrid Tomato (टमाटर)": "Firm, bright-red hybrid tomatoes that hold up well in cooking. Perfect for gravies, salads, and everyday meals.",
    "Jackfruit Raw / Kathal (कटहल)": "Fresh raw jackfruit with a meaty texture. Perfect for kathal sabzi, biryani, and rich curries.",
    "Kakri / Long Melon (ककड़ी)": "Long, crunchy kakri with a cooling, mild taste. Perfect for salads and refreshing summer snacking.",
    "Kundru / Ivy Gourd (कुंदरू)": "Fresh and naturally grown kundru with a tender bite and mild taste. Perfect for stir-fries, dry sabzi, and everyday home-style meals.",
    "Ladyfinger / Bhindi (भिंडी)": "Tender, fresh bhindi with a crisp snap. Perfect for bhindi masala, fries, and everyday sabzi.",
    "Long Bottle Gourd / Lambi Lauki (लंबी लौकी)": "Fresh, tender long lauki with soft flesh. Perfect for sabzi, kofta, dal, and light home meals.",
    "Mushroom Button (मशरूम)": "Fresh, firm button mushrooms with an earthy taste. Perfect for curries, stir-fries, soups, and pizzas.",
    "Normal Potato / Aloo (आलू)": "Versatile, everyday potatoes with a soft texture. Perfect for curries, parathas, fries, and endless dishes.",
    "Onion (प्याज)": "Firm, pungent onions — the base of Indian cooking. Perfect for gravies, salads, and everyday tadka.",
    "Orange Carrot / Gajar (गाजर)": "Sweet, crunchy orange carrots full of goodness. Perfect for salads, halwa, juices, and sabzi.",
    "Parwal / Pointed Gourd (परवल)": "Tender parwal with a mild, pleasant flavour. Perfect for bhujia, stuffed sabzi, and light curries.",
    "Peas (मटर)": "Sweet, tender green peas freshly shelled. Perfect for pulao, matar paneer, and everyday sabzi.",
    "Pumpkin / Kaddu (कद्दू)": "Fresh pumpkin with sweet, tender flesh. Perfect for sabzi, halwa, and comforting home cooking.",
    "Purple Yam / Ratalu (रतालू)": "Wholesome ratalu with a soft, starchy texture. Perfect for fry, sabzi, and traditional fasting dishes.",
    "Radish / Mooli (मूली)": "Crisp, peppery white radish with fresh crunch. Perfect for salads, parathas, and sabzi.",
    "Raw Banana (कच्चा केला)": "Firm raw bananas with a starchy texture. Perfect for kofta, chips, and traditional sabzi.",
    "Raw Papaya (कच्चा पपीता)": "Firm, green raw papaya with a mild taste. Perfect for thoran, salads, and healthy sabzi.",
    "Red Carrot / Lal Gajar (लाल गाजर)": "Juicy, sweet red carrots at their winter best. Perfect for gajar halwa, kanji, and salads.",
    "Red Potato / Red Aloo (लाल आलू)": "Red-skinned potatoes with a firm, creamy texture. Perfect for curries, roasts, and everyday cooking.",
    "Ridge Gourd / Turai (तोरई)": "Tender ridge gourd with soft, mild flesh. Perfect for light sabzi, dal, and chutney.",
    "Ripe Pumpkin (पका कद्दू)": "Sweet, ripe pumpkin with rich golden flesh. Perfect for sabzi, halwa, and soups.",
    "Round Brinjal / Gol Baingan (गोल बैंगन)": "Plump, glossy round brinjals with rich flavour. Perfect for bharta, stuffed baingan, and curries.",
    "Small Green Brinjal (हरे छोटे बैंगन)": "Small, tender green brinjals with few seeds. Perfect for bharwan baingan and everyday sabzi.",
    "Small Round Brinjal / Bharwan Baingan (भरवां बैंगन)": "Small round brinjals perfect for stuffing. Ideal for bharwan baingan and rich masala curries.",
    "Spring Onion / Hara Pyaz (हरा प्याज)": "Fresh spring onions with crisp greens and mild bulbs. Perfect for stir-fries, garnishes, and Indo-Chinese dishes.",
    "Sweet Corn (मक्का)": "Juicy, tender sweet corn with a naturally sweet bite. Perfect for boiling, grilling, soups, and salads.",
    "Sweet Potato / Shakarkand (शकरकंद)": "Naturally sweet shakarkand with soft, creamy flesh. Perfect for chaat, roasting, and fasting dishes.",
    "Thick Pickle Chilli (मोटी मिर्च)": "Thick, mild chillies ideal for pickling. Perfect for stuffed mirch pickle and tangy preserves.",
    "Tinda / Round Gourd (टिंडा)": "Tender round tinda with soft, mild flesh. Perfect for masala sabzi and light home cooking.",
    "Turnip (शलजम)": "Crisp, mildly sweet turnips at their winter best. Perfect for sabzi, pickles, and hearty stews.",

    # ---------------- Leafy Greens ----------------
    "Bathua Greens (बथुआ का साग)": "Fresh, tender bathua leaves with an earthy taste. Perfect for saag, raita, and parathas.",
    "Colocasia Leaves (अरबी के पत्ते)": "Broad, fresh arbi leaves. Perfect for patra, pakoras, and traditional regional dishes.",
    "Coriander / Dhaniya (धनिया)": "Fragrant, fresh coriander leaves. Perfect for garnishing, chutneys, and adding aroma to any dish.",
    "Curry Leaves / Kadi Patta (कढ़ी पत्ता)": "Aromatic fresh curry leaves. Perfect for tadka, sambar, and South Indian tempering.",
    "Dill Leaves (सोया का साग)": "Feathery, aromatic dill leaves. Perfect for saag, dal, and flavourful parathas.",
    "Green Amaranth Leaves (हरी चौलाई साग)": "Fresh and nutritious green amaranth leaves rich in iron and essential nutrients. Perfect for saag, stir-fry, and healthy daily meals.",
    "Malabar Spinach / Poi Greens (पोई का साग)": "Tender, glossy poi greens. Perfect for saag, stir-fries, and wholesome regional dishes.",
    "Methi / Fenugreek Leaves (मेथी)": "Fresh, slightly bitter methi leaves. Perfect for methi paratha, aloo methi, and dals.",
    "Mint / Pudina (पुदीना)": "Cool, fragrant mint leaves. Perfect for chutneys, raita, drinks, and garnishing.",
    "Mustard Greens (सरसों का साग)": "Fresh mustard greens with a robust flavour. Perfect for the classic sarson ka saag with makki roti.",
    "Red Amaranth Leaves (लाल चौलाई साग)": "Vibrant red amaranth leaves rich in iron. Perfect for saag, stir-fries, and healthy meals.",
    "Spinach / Palak (पालक)": "Fresh, tender palak packed with iron. Perfect for palak paneer, saag, dal, and smoothies.",
    "Water Spinach / Karmi Saag (करमी का साग)": "Tender water spinach with crisp stems. Perfect for stir-fries and light, healthy saag.",

    # ---------------- Exotic ----------------
    "Avocado (एवोकाडो)": "Creamy, buttery avocados rich in healthy fats. Perfect for guacamole, toast, salads, and smoothies.",
    "Blueberry (ब्लूबेरी)": "Plump, antioxidant-rich blueberries with a sweet-tart burst. Perfect for smoothies, desserts, and healthy snacking.",
    "Broccoli (ब्रोकली)": "Fresh, firm broccoli with tight green florets. Perfect for stir-fries, soups, and healthy sides.",
    "Dragon Fruit (ड्रैगन फ्रूट)": "Striking dragon fruit with mildly sweet, refreshing flesh. Perfect for fruit bowls, smoothies, and salads.",
    "Green Zucchini (हरी ज़ुकीनी)": "Tender green zucchini with a mild taste. Perfect for grilling, stir-fries, pastas, and sautés.",
    "Karonda / Natal Plum (करौंदा)": "Tart, crisp karonda with a sharp tang. Perfect for pickles, chutneys, and traditional preserves.",
    "Kiwi (कीवी)": "Tangy-sweet kiwi with vitamin-rich green flesh. Perfect for snacking, fruit salads, and smoothies.",
    "Kohlrabi (गांठ गोभी)": "Crisp kohlrabi with a mild, sweet crunch. Perfect for salads, sabzi, and stir-fries.",
    "Lotus Stem (कमल ककड़ी)": "Crunchy lotus stem with a delicate flavour. Perfect for kamal kakdi sabzi, kofta, and stir-fries.",
    "Passion Fruit (पैशन फ्रूट)": "Aromatic passion fruit with tangy, juicy pulp. Perfect for juices, desserts, and exotic drinks.",
    "Red & Yellow Capsicum (लाल पीली शिमला मिर्च)": "Sweet, colourful bell peppers with a crisp bite. Perfect for salads, stir-fries, and vibrant curries.",
    "Strawberry (स्ट्रॉबेरी)": "Juicy, fragrant strawberries with a sweet-tart taste. Perfect for desserts, shakes, and fresh snacking.",
    "Teasel Gourd / Kakrol (काकरोल)": "Tender teasel gourd with a mild taste. Perfect for fries, stir-fries, and regional sabzi.",
    "Water Chestnut / Singhada (सिंघाड़ा)": "Crunchy fresh water chestnuts with a mild, sweet taste. Perfect for snacking, sabzi, and fasting recipes.",
}
